---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_name }}
  description: ${{ values.component_description }}
  annotations:
    github.com/project-slug: ${{ values.github_org }}/${{ values.component_name }}
spec:
  type: iac
  lifecycle: ${{ values.lifecycle }}
  owner: group:${{ values.owner_name }}
  system: system:${{ values.system_name }}
