name: Branches
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup job workspace
        uses: ServerlessOpsIO/gha-setup-workspace@v1

      - name: Assume AWS credentials
        uses: ServerlessOpsIO/gha-assume-aws-credentials@v1
        with:
          build_aws_account_id: {% raw %}${{ secrets.AWS_CICD_ACCOUNT_ID }}{% endraw %}

      - name: Install AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Validate template
        run: sam validate --lint

      - name: Build deployment artifact
        run: sam build

      - name: Store artifacts
        uses: ServerlessOpsIO/gha-store-artifacts@v1
        with:
          use_aws_sam: true

  deploy:
    needs:
      - build

    environment: production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup job workspace
        uses: ServerlessOpsIO/gha-setup-workspace@v1
        with:
          checkout_artifact: true

      - name: Assume AWS credentials
        uses: ServerlessOpsIO/gha-assume-aws-credentials@v1
        with:
          build_aws_account_id: {% raw %}${{ secrets.AWS_CICD_ACCOUNT_ID }}{% endraw %}
          deploy_aws_account_id: {% raw %}${{ secrets.DEPLOYMENT_ACCOUNT_ID }}{% endraw %}

      - name: Deploy via AWS SAM
        uses: ServerlessOpsIO/gha-deploy-aws-sam@v1
        with:
          aws_account_id: {% raw %}${{ secrets.DEPLOYMENT_ACCOUNT_ID }}{% endraw %}
          env_json: {% raw %}${{ toJson(env) }}{% endraw %}
          vars_json: {% raw %}${{ toJson(vars) }}{% endraw %}
          secrets_json: {% raw %}${{ toJson(secrets) }}{% endraw %}
